@startuml

!include ../style.plantuml

actor A as "User A"
actor B as "User B"
participant "Service" as Service #FFFFFF
participant "IdAM API" as IdAM
participant "ForgeRock AM" as AM #76D6FF
participant "ForgeRock IM" as IM #CFFB8C

== Resource Ownership and Grant Registration ==

A -> Service: Data Creating Request
activate Service
note over Service: Store Data, etc.
Service -> IdAM: Record Ownership Request
activate IdAM
IdAM -> IM: Create Ownership Object Request
note over IM: Store Identity, URI, etc.
IM -> IdAM: Create Ownership Object Response
IdAM -> Service: Record Ownership Response
Service -> IdAM: Record Grant(s) Request
note over Service, IdAM: Grant Read Action to User B
IdAM -> IM: Create Grant Object(s) Request
note over IM: Store Identity/Group, Action, URI, etc.
IM -> IdAM: Create Grant Object(s) Response
IdAM -> Service: Record Grant(s) Response
deactivate IdAM
Service -> A: Data Creating Response
deactivate Service

... Later ...

== Resource Usage ==

B -> Service: Data Read Request
activate Service
Service -> IdAM: Access Control Request
note over Service, IdAM: Access Control Request contains Identity, Resource and Action data
activate IdAM
IdAM -> AM: Policy Request
activate AM
AM -> IM: Object Retrieval Request(s)
IM -> AM: Object Retrieval Response(s)
activate AM
note over AM: Policy Evaluates Objects including registered Grants
note over AM: User has required Grant (directly or through Group, etc.)
AM -> AM: Policy Evaluation
deactivate AM
AM -> IdAM: Policy Response
deactivate AM
IdAM -> Service: Access Control Response
deactivate IdAM
Service -> Service: Access Control Enforcement
Service -> B: Data Usage Response

@enduml
