@startuml

!include ../style.plantuml

participant "Service" as Service #FFFFFF
participant "IdAM API" as IdAM
participant "ForgeRock IM" as IM #CFFB8C
participant "ForgeRock Connector" as Connector #FFD479
participant "Citizen CRM" as CRM #C0C0C0

Service -> IdAM: Identity Modification Request
activate IdAM
IdAM -> IM: User Object Modification Request
IM -> IdAM: User Object Modification Response
IdAM -> Service: Identity Modification Response
deactivate IdAM
...Asynchronous...
IM -> Connector: Synchronisation
Connector -> CRM: Modification

@enduml
