@startuml

actor User
participant IdAM
participant Service
database "Service Data"
participant "Access Control"
database "Access Control Data"

User -> IdAM: Authentication Request
note left: Elides Sign-In Process
IdAM --> User: Authentication Credentials

... Later ...

User -> Service: Request with Credentials
Service -> "Service Data": Context Query
"Service Data" -> Service: Context Result
Service -> "Access Control": Permission Request
note right: Using Relevant Context Data
"Access Control" --> "Access Control Data": Permission Query
"Access Control Data" --> "Access Control": Permission Result
hnote over "Access Control", "Access Control Data": Access Control Logic
"Access Control" -> Service: Permission Response

alt Sufficient Permission

... Processing etc. ...

Service -> User: Response

else Insufficient Permission

Service -> User: Rejection
note right: May Trigger Uplift

end

@enduml
