@startuml

skinparam backgroundColor #fafafa

skinparam sequence {
  actorBorderThickness 1

  box {
    backgroundColor #ff0000
    borderColor #00ff00
  }

  group {
    backgroundColor #cccccc
    bodyBackgroundColor #dddddd
    borderColor #333333
    borderThickness 1
    shadowing false
  }

  divider {
    backgroundColor #eeeeee
    borderThickness 1
  }

  participant {
    backgroundColor #cccccc
    borderColor #333333
    borderThickness 1
    shadowing false
  }
}

@enduml
